name: "🐛 Bug Report"
description: We broke something, again
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for reporting an issue!** Please make sure you read our [issue guidelines](https://github.com/PiresFelipe/QualiTag/blob/main/.github/CONTRIBUTING.md) first, then fill out the fields below.

        If you’re unsure whether the issue you’re having is a bug, you can post in [Discussions](https://github.com/PiresFelipe/QualiTag/discussions) instead.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please ensure you have completed all of the following.
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/PiresFelipe/QualiTag/blob/main/.github/CONTRIBUTING.md#i-want-to-contribute).
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/PiresFelipe/QualiTag/blob/main/.github/CODE_OF_CONDUCT.md).
          required: true
        - label: I have searched for [existing issues](https://github.com/PiresFelipe/QualiTag/issues) that already suggests something similar, without success.
          required: true

  - type: textarea
    id: bug-steps
    attributes:
      label: What are the steps to reproduce this issue?
      placeholder: |
        1. Make new project
        2. Run `make package`
        3. …
        4. See error
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: What happens?
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: bug-expectation
    attributes:
      label: What were you expecting to happen?
      description: A clear and concise description of what was supposed to happen.
    validations:
      required: true

  - type: textarea
    id: bug-logs
    attributes:
      label: Paste any relevant logs, error output, etc.
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
        (If it’s long, please paste to https://gist.github.com/ and insert the link here.)
      render: shell

  - type: textarea
    id: bug-context
    attributes:
      label: Additional context
      description: Add any other context you can provide about the problem here.

  - type: markdown
    attributes:
      value: |
        ----
        
        # Details of your host machine (the device you’re running QualiTag on)

  - type: dropdown
    id: host-os
    attributes:
      label: What OS are you seeing the problem on?
      options:
        - Windows
        - macOS
        - Linux/WSL
      multiple: true
    validations:
      required: true

  - type: input
    id: host-os-version
    attributes:
      label: What OS version does it have installed?
      placeholder: "e.g. macOS 11.5.1"
    validations:
      required: true

  - type: input
    id: host-toolchain
    attributes:
      label: What toolchain and version are you using?
      description: |
        If your host machine is running macOS, specify the version of Xcode you’re using here. You can find out by selecting Xcode in Finder, then click File &rarr; Get Info.  
        Otherwise, specify the toolchain you’re using – either the clang version number, or if you’re not sure, just specify where you downloaded it from.
      placeholder: "e.g. Xcode 12.5, or clang 12.0.5"
    validations:
      required: true

  - type: input
    id: host-sdk
    attributes:
      label: Which SDK version are you using?
      placeholder: "e.g. iOS 14.0"
    validations:
      required: true