name: Code Format

# Dispara o workflow em push para as branches main e dev, e em pull_request
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  # Job: Formatar o código
  format:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Instalação do Python e dependências
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Versão do Python

      # Instala as dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      # Rodar o Black para formatar o código
      - name: Run Black
        run: |
          black --check .
