name: Format Python Code
on: push
  branches:
    - main
    - dev
jobs:
  python-code-format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Display Python version
        run: python --version
      - name: Install packages
        run: pip install black autopep8 isort
      - name: Formatter
        run: |
          black ./qualitag
          autopep8 --recursive --in-place --aggressive --aggressive ./qualitag
          isort ./qualitag